// UwU XD '-' =) ;) |.| 'x' *-* S2 <3 >_< >.< Shakira! Bunny hop Slide jump
//
// Faça um algoritmo que leia 30 númoeros reais em vetor e depois mostre os nú
// meros localizados nas posições ímpares
//

algoritmo "Modelo"

var
   i:inteiro

   v1:vetor[1..10] de inteiro
   
inicio

   
   para i <- 1 ate 10 faca
    escreva ("Informe um número: ")
    leia (v1 [i])
   fimpara
   
   para i <- 1 ate 10 passo 2 faca
    escreva (v1 [i])
   fimpara

   
fimalgoritmo
