// Faça um programa que fique mostrando a mensagem "Comando enquanto".
// A cada frase mostrada, dê a opção para que o usuário escolher se continua
//ou não S- Continuar N- Não continuar

algoritmo "Continuar"

var
   letra: literal
inicio

   

   enquanto letra <> "N" faca
   escreval ("Comando enquanto")
   escreva ("Você deseja: S- Continuar ou N- Não continuar: ")
   leia (letra)
   fimenquanto

fimalgoritmo
