//  Faça um algoritmo que solicite N números inteiros
// Até que o número 0 (zero) seja digitado.
// Ao final o algoritmo deve informar o maior numero digitado


algoritmo "Número maior"

var
   n, maior:inteiro
inicio

   n <- 1
   
   enquanto n <> 0 faca
   escreval ("Informe o número inteiro: ")
   leia(n)
   
   se (n > maior) entao
    maior <- n
    
   fimse
   fimenquanto



  escreva ("O maior número é: ", maior)
   

fimalgoritmo
